--
-- PostgreSQL database dump
--


-- Dumped from database version 16.13 (Ubuntu 16.13-1.pgdg24.04+1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.postcodes DROP CONSTRAINT IF EXISTS postcodes_state_id_fkey;
ALTER TABLE IF EXISTS ONLY public.postcodes DROP CONSTRAINT IF EXISTS postcodes_country_id_fkey;
ALTER TABLE IF EXISTS ONLY public.postcodes DROP CONSTRAINT IF EXISTS postcodes_city_id_fkey;
DROP INDEX IF EXISTS public.postcodes_state_id_idx;
DROP INDEX IF EXISTS public.postcodes_country_id_code_idx;
DROP INDEX IF EXISTS public.postcodes_code_idx;
DROP INDEX IF EXISTS public.postcodes_city_id_idx;
ALTER TABLE IF EXISTS ONLY public.postcodes DROP CONSTRAINT IF EXISTS postcodes_pkey;
DROP TABLE IF EXISTS public.postcodes;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: postcodes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.postcodes (
    id bigint NOT NULL,
    code character varying(20) NOT NULL,
    country_id bigint NOT NULL,
    country_code character(2) NOT NULL,
    state_id bigint,
    state_code character varying(255),
    city_id bigint,
    locality_name character varying(255),
    type character varying(32),
    latitude numeric(10,8),
    longitude numeric(11,8),
    source character varying(64),
    "wikiDataId" character varying(255),
    created_at timestamp without time zone DEFAULT '2014-01-01 12:01:01'::timestamp without time zone NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    flag smallint DEFAULT 1 NOT NULL
);


--
-- Name: TABLE postcodes; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.postcodes IS 'Postal codes (issue #1039) - Tier 4: one row per postcode';


--
-- Name: COLUMN postcodes.code; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.postcodes.code IS 'The postal code value (alphanumeric, country-specific format)';


--
-- Name: COLUMN postcodes.locality_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.postcodes.locality_name IS 'Human-readable place name associated with the postcode';


--
-- Name: COLUMN postcodes.type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.postcodes.type IS 'Granularity: full | outward | sector | district | area';


--
-- Name: COLUMN postcodes.source; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.postcodes.source IS 'Originating data source for license/attribution tracking (e.g. openplz, wikidata, census)';


--
-- Name: COLUMN postcodes."wikiDataId"; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.postcodes."wikiDataId" IS 'Wikidata Q-ID for cross-referencing';


--
-- Name: postcodes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.postcodes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.postcodes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: postcodes; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Name: postcodes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.postcodes_id_seq', 1, false);


--
-- Name: postcodes postcodes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.postcodes
    ADD CONSTRAINT postcodes_pkey PRIMARY KEY (id);


--
-- Name: postcodes_city_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX postcodes_city_id_idx ON public.postcodes USING btree (city_id);


--
-- Name: postcodes_code_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX postcodes_code_idx ON public.postcodes USING btree (code);


--
-- Name: postcodes_country_id_code_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX postcodes_country_id_code_idx ON public.postcodes USING btree (country_id, code);


--
-- Name: postcodes_state_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX postcodes_state_id_idx ON public.postcodes USING btree (state_id);


--
-- Name: postcodes postcodes_city_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.postcodes
    ADD CONSTRAINT postcodes_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities(id) ON DELETE SET NULL;


--
-- Name: postcodes postcodes_country_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.postcodes
    ADD CONSTRAINT postcodes_country_id_fkey FOREIGN KEY (country_id) REFERENCES public.countries(id);


--
-- Name: postcodes postcodes_state_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.postcodes
    ADD CONSTRAINT postcodes_state_id_fkey FOREIGN KEY (state_id) REFERENCES public.states(id) ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--


