--
-- PostgreSQL database dump
--


-- Dumped from database version 16.13 (Ubuntu 16.13-1.pgdg24.04+1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.subregions DROP CONSTRAINT IF EXISTS subregions_region_id_fkey;
ALTER TABLE IF EXISTS ONLY public.states DROP CONSTRAINT IF EXISTS states_country_id_fkey;
ALTER TABLE IF EXISTS ONLY public.countries DROP CONSTRAINT IF EXISTS countries_subregion_id_fkey;
ALTER TABLE IF EXISTS ONLY public.countries DROP CONSTRAINT IF EXISTS countries_region_id_fkey;
ALTER TABLE IF EXISTS ONLY public.cities DROP CONSTRAINT IF EXISTS cities_state_id_fkey;
ALTER TABLE IF EXISTS ONLY public.cities DROP CONSTRAINT IF EXISTS cities_country_id_fkey;
DROP INDEX IF EXISTS public.subregions_region_id_idx;
DROP INDEX IF EXISTS public.states_country_id_idx;
DROP INDEX IF EXISTS public.countries_subregion_id_idx;
DROP INDEX IF EXISTS public.countries_region_id_idx;
DROP INDEX IF EXISTS public.cities_state_id_idx;
DROP INDEX IF EXISTS public.cities_country_id_idx;
ALTER TABLE IF EXISTS ONLY public.subregions DROP CONSTRAINT IF EXISTS subregions_pkey;
ALTER TABLE IF EXISTS ONLY public.states DROP CONSTRAINT IF EXISTS states_pkey;
ALTER TABLE IF EXISTS ONLY public.regions DROP CONSTRAINT IF EXISTS regions_pkey;
ALTER TABLE IF EXISTS ONLY public.countries DROP CONSTRAINT IF EXISTS countries_pkey;
ALTER TABLE IF EXISTS ONLY public.cities DROP CONSTRAINT IF EXISTS cities_pkey;
DROP TABLE IF EXISTS public.subregions;
DROP TABLE IF EXISTS public.states;
DROP TABLE IF EXISTS public.regions;
DROP TABLE IF EXISTS public.countries;
DROP TABLE IF EXISTS public.cities;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cities (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    state_id bigint NOT NULL,
    state_code character varying(255) NOT NULL,
    country_id bigint NOT NULL,
    country_code character(2) NOT NULL,
    type character varying(191),
    level integer,
    parent_id bigint,
    latitude numeric(10,8) NOT NULL,
    longitude numeric(11,8) NOT NULL,
    native character varying(255),
    population bigint,
    timezone character varying(255),
    translations text,
    created_at timestamp without time zone DEFAULT '2014-01-01 12:01:01'::timestamp without time zone NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    flag smallint DEFAULT 1 NOT NULL,
    "wikiDataId" character varying(255)
);


--
-- Name: COLUMN cities.timezone; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.cities.timezone IS 'IANA timezone identifier (e.g., America/New_York)';


--
-- Name: COLUMN cities."wikiDataId"; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.cities."wikiDataId" IS 'Rapid API GeoDB Cities';


--
-- Name: cities_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: countries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.countries (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    iso3 character(3),
    numeric_code character(3),
    iso2 character(2),
    phonecode character varying(255),
    capital character varying(255),
    currency character varying(255),
    currency_name character varying(255),
    currency_symbol character varying(255),
    tld character varying(255),
    native character varying(255),
    population bigint,
    gdp bigint,
    region character varying(255),
    region_id bigint,
    subregion character varying(255),
    subregion_id bigint,
    nationality character varying(255),
    area_sq_km double precision,
    postal_code_format character varying(255),
    postal_code_regex character varying(255),
    timezones text,
    translations text,
    latitude numeric(10,8),
    longitude numeric(11,8),
    emoji character varying(191),
    "emojiU" character varying(191),
    created_at timestamp without time zone,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    flag smallint DEFAULT 1 NOT NULL,
    "wikiDataId" character varying(255)
);


--
-- Name: COLUMN countries."wikiDataId"; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.countries."wikiDataId" IS 'Rapid API GeoDB Cities';


--
-- Name: countries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.countries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.countries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: regions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.regions (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    translations text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    flag smallint DEFAULT 1 NOT NULL,
    "wikiDataId" character varying(255)
);


--
-- Name: COLUMN regions."wikiDataId"; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.regions."wikiDataId" IS 'Rapid API GeoDB Cities';


--
-- Name: regions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.regions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.regions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: states; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.states (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    country_id bigint NOT NULL,
    country_code character(2) NOT NULL,
    fips_code character varying(255),
    iso2 character varying(255),
    iso3166_2 character varying(10),
    type character varying(191),
    level integer,
    parent_id bigint,
    native character varying(255),
    latitude numeric(10,8),
    longitude numeric(11,8),
    timezone character varying(255),
    translations text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    flag smallint DEFAULT 1 NOT NULL,
    "wikiDataId" character varying(255),
    population character varying(255)
);


--
-- Name: COLUMN states.timezone; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.states.timezone IS 'IANA timezone identifier (e.g., America/New_York)';


--
-- Name: COLUMN states."wikiDataId"; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.states."wikiDataId" IS 'Rapid API GeoDB Cities';


--
-- Name: states_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.states ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.states_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subregions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subregions (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    translations text,
    region_id bigint NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    flag smallint DEFAULT 1 NOT NULL,
    "wikiDataId" character varying(255)
);


--
-- Name: COLUMN subregions."wikiDataId"; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.subregions."wikiDataId" IS 'Rapid API GeoDB Cities';


--
-- Name: subregions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.subregions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subregions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cities cities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT cities_pkey PRIMARY KEY (id);


--
-- Name: countries countries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.countries
    ADD CONSTRAINT countries_pkey PRIMARY KEY (id);


--
-- Name: regions regions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.regions
    ADD CONSTRAINT regions_pkey PRIMARY KEY (id);


--
-- Name: states states_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.states
    ADD CONSTRAINT states_pkey PRIMARY KEY (id);


--
-- Name: subregions subregions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subregions
    ADD CONSTRAINT subregions_pkey PRIMARY KEY (id);


--
-- Name: cities_country_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX cities_country_id_idx ON public.cities USING btree (country_id);


--
-- Name: cities_state_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX cities_state_id_idx ON public.cities USING btree (state_id);


--
-- Name: countries_region_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX countries_region_id_idx ON public.countries USING btree (region_id);


--
-- Name: countries_subregion_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX countries_subregion_id_idx ON public.countries USING btree (subregion_id);


--
-- Name: states_country_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX states_country_id_idx ON public.states USING btree (country_id);


--
-- Name: subregions_region_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX subregions_region_id_idx ON public.subregions USING btree (region_id);


--
-- Name: cities cities_country_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT cities_country_id_fkey FOREIGN KEY (country_id) REFERENCES public.countries(id);


--
-- Name: cities cities_state_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT cities_state_id_fkey FOREIGN KEY (state_id) REFERENCES public.states(id);


--
-- Name: countries countries_region_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.countries
    ADD CONSTRAINT countries_region_id_fkey FOREIGN KEY (region_id) REFERENCES public.regions(id);


--
-- Name: countries countries_subregion_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.countries
    ADD CONSTRAINT countries_subregion_id_fkey FOREIGN KEY (subregion_id) REFERENCES public.subregions(id);


--
-- Name: states states_country_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.states
    ADD CONSTRAINT states_country_id_fkey FOREIGN KEY (country_id) REFERENCES public.countries(id);


--
-- Name: subregions subregions_region_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subregions
    ADD CONSTRAINT subregions_region_id_fkey FOREIGN KEY (region_id) REFERENCES public.regions(id);


--
-- PostgreSQL database dump complete
--


