application:
  name: countries-states-cities-database
  path_log: "/logs"

database:
  mysql:
    hostname: "127.0.0.1"
    port: "3306"
    username: "root"
    password: "root"
    database: "world"
