name: 🐛 Bug Report
description: Report a bug or incorrect data in the database
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: dropdown
    id: bug-type
    attributes:
      label: Bug Type
      description: What type of bug are you reporting?
      options:
        - Incorrect Data (wrong city/state/country information)
        - Missing Data (city/state/country not in database)
        - Duplicate Data (duplicate entries)
        - API Issue
        - Export Format Issue
        - Other
    validations:
      required: true

  - type: input
    id: affected-entity
    attributes:
      label: Affected Entity
      description: Which country/state/city is affected? (e.g., "San Francisco, CA, USA")
      placeholder: "City, State, Country"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Tell us what's wrong
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What should the correct data be?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: What is the current incorrect data?
    validations:
      required: true

  - type: textarea
    id: source
    attributes:
      label: Source/Reference
      description: Please provide a reliable source for the correct information (WikiData, Wikipedia, official government site, etc.)
      placeholder: |
        - WikiData: https://www.wikidata.org/wiki/...
        - Wikipedia: https://en.wikipedia.org/wiki/...
        - Official source: ...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
    validations:
      required: false
